
POST http://192.168.5.141:80/user/register
Content-Type: application/json

{
   "username": "penis",
   "password": "penis"
}

###

POST http://192.168.5.141:80/user/login
Content-Type: application/json

{
   "username": "test",
   "password": "test"
}

###
POST http://192.168.5.141:80/posts/create
Content-Type: application/json

{
   "postContent": "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.",
   "postTitle": "uwupost"
}

###

GET http://192.168.5.141:80/posts/get